// Iconos pixel-art dibujados a mano (grillas de 8x8), pensados para el look
// del mockup de referencia. No se genero ninguna imagen: cada "X" es un
// pixel pintado, cada "." un pixel transparente -- ver PixelIcon.tsx.
export type PixelGlyph = readonly string[];

export const GLYPHS = {
  CAR: [
    '...XX...',
    '...XX...',
    '..XXXX..',
    '..XXXX..',
    '.XXXXXX.',
    '.XXXXXX.',
    'XXXXXXXX',
    'XXXXXXXX',
  ],
  EXCLAIM: [
    '..XXXX..',
    '..XXXX..',
    '..XXXX..',
    '..XXXX..',
    '..XXXX..',
    '........',
    '..XXXX..',
    '..XXXX..',
  ],
  PAW: [
    'XX....XX',
    'XXX..XXX',
    '.XXXXXX.',
    '..XXXX..',
    '..XXXX..',
    '.XXXXXX.',
    'XXX..XXX',
    'XX....XX',
  ],
  HEART: [
    '.XX.XX..',
    'XXXXXXXX',
    'XXXXXXXX',
    'XXXXXXXX',
    '.XXXXXX.',
    '..XXXX..',
    '...XX...',
    '........',
  ],
  STAR: [
    '...XX...',
    '..XXXX..',
    '.XXXXXX.',
    'XXXXXXXX',
    'XXXXXXXX',
    '.XXXXXX.',
    '..XXXX..',
    '...XX...',
  ],
  CALENDAR: [
    '.X....X.',
    'XXXXXXXX',
    'X......X',
    'X.XXXX.X',
    'X.X..X.X',
    'X.XXXX.X',
    'X......X',
    'XXXXXXXX',
  ],
  MEGAPHONE: [
    '......XX',
    '.....XXX',
    '....XXXX',
    'XXXXXXXX',
    'XXXXXXXX',
    '....XXXX',
    '.....XXX',
    '......XX',
  ],
  TAG: [
    'XXXXXX..',
    'X....X..',
    'X.XX.X..',
    'X.XX.X..',
    'X....X..',
    'XXXXXX..',
    '........',
    '........',
  ],
  DOTS: [
    '........',
    '........',
    '........',
    'XX.XX.XX',
    'XX.XX.XX',
    '........',
    '........',
    '........',
  ],
  FORK: [
    'X.X.X...',
    'X.X.X...',
    'X.X.X...',
    'XXXXX...',
    '..X.....',
    '..X.....',
    '..X.....',
    '..X.....',
  ],
  SHOP: [
    '.XXXXXX.',
    'XXXXXXXX',
    'X......X',
    'X.XXXX.X',
    'X.X..X.X',
    'X.X..X.X',
    'X.XXXX.X',
    'XXXXXXXX',
  ],
  BED: [
    '........',
    'X.......',
    'X.XXXX..',
    'X.X..X..',
    'XXXXXXXX',
    'X......X',
    'X......X',
    '........',
  ],
  TREE: [
    '..XXXX..',
    '.XXXXXX.',
    'XXXXXXXX',
    'XXXXXXXX',
    '.XXXXXX.',
    '...XX...',
    '...XX...',
    '..XXXX..',
  ],
  CAMERA: [
    '.XXXXX..',
    'X.....X.',
    'XXXXXXX.',
    'X.XXX.X.',
    'X.X.X.X.',
    'X.XXX.X.',
    'XXXXXXX.',
    '........',
  ],
  CROSS_SOLID: [
    '..XX....',
    '..XX....',
    'XXXXXX..',
    'XXXXXX..',
    'XXXXXX..',
    '..XX....',
    '..XX....',
    '........',
  ],
  CROSS_HOLLOW: [
    '..XX....',
    '..XX....',
    'XXXXXX..',
    'X.XX.X..',
    'X.XX.X..',
    'XXXXXX..',
    '..XX....',
    '........',
  ],
  CAP: [
    'XXXXXXXX',
    'XXXXXXXX',
    '...XX...',
    '..XXXX..',
    '..XXXX..',
    '...XX...',
    '....X...',
    '....X...',
  ],
  COIN: [
    '.XXXXXX.',
    'XX....XX',
    'X.XXXX.X',
    'X.X..X.X',
    'X.X..X.X',
    'X.XXXX.X',
    'XX....XX',
    '.XXXXXX.',
  ],
  BUS: [
    '.XXXXXX.',
    'XXXXXXXX',
    'X.XX.XX.',
    'X......X',
    'XXXXXXXX',
    '.X.XX.X.',
    '.X.XX.X.',
    '........',
  ],
  PIN: [
    '..XXXX..',
    '.XXXXXX.',
    'XXX..XXX',
    'XXX..XXX',
    '.XXXXXX.',
    '..XXXX..',
    '...XX...',
    '...XX...',
  ],
  NEWSPAPER: [
    'XXXXXXX.',
    'X.....X.',
    'X.XXX.X.',
    'X.....X.',
    'X.XXX.X.',
    'X.....X.',
    'XXXXXXX.',
    '........',
  ],
  PLUS: [
    '........',
    '...XX...',
    '...XX...',
    'XXXXXXXX',
    'XXXXXXXX',
    '...XX...',
    '...XX...',
    '........',
  ],
  COMPASS: [
    '.XXXXXX.',
    'X......X',
    'X..XX..X',
    'X.X..X.X',
    'X.X..X.X',
    'X..XX..X',
    'X......X',
    '.XXXXXX.',
  ],
  PERSON: [
    '..XXXX..',
    '.X....X.',
    '.X....X.',
    '..XXXX..',
    '........',
    '.XXXXXX.',
    'XXXXXXXX',
    'XXXXXXXX',
  ],
} as const satisfies Record<string, PixelGlyph>;

export type GlyphName = keyof typeof GLYPHS;
